#!/bin/bash
# usage: $0 dir [mencoder-options]
# encodes all jpg files in dir as mjpeg-avi (dir.avi)

in=$1/*.jpg
out=${1%/}
out=${out##*/}.avi
shift

mencoder "mf://$in" -mf fps=25 -ovc copy -o $out $*
