#!/bin/bash
# usage: $0 dir [n]
# temp directory thumbnailer, thumbnails and html-outputs every nth image [all images]

# add process-images $1 to start video encode and stuff
ls-nth ${2:-1} ${1:-.}/* | xargs process-images
