#!/bin/bash
# usage: $0 files/directories
# processes incoming image files and directories
# NOTE: other scripts need be in path

# original->thumbnail/video rename sed regexp magic
thre=s/^i/s/
vre=s/^i/v/

# $0 outfile
mk-outdir () {
	# outdir is available out of function, too, hm
	outdir=$(dirname $1)
	mkdir -p $outdir
}

for f in $*; do
	# TODO: only every 6th image into html (here or by caller?)
	if [ ! -d $f ]; then
		# get the HHMM counter
		# TODO compare to previous and do the 6th thing
		#hhmm=${f::4}
		#base=$(basename $f)
		out=$(echo $f | sed $thre)
		#outdir=$(dirname $out)
		mk-outdir $out

		# check if thumbnail already exists and skip regenerating it
		[ -e $out ] || gen-thumbnail $outdir $f
		html-img $f $out
	else
		echo "<br />"
		# TODO: on new day first image, insert margin-left if not at midnight?

		# on new day, start a new video and insert <video>
		out=$(echo $f | sed $vre).ogv
		mk-outdir $out
		html-video $out

		echo NOW ENCODING: $f -\> $out > /dev/stderr

		# start encoding video!
		# TODO and stop previous day :)
		wait-files $f cat | fftheora-pipe $out &> $outdir/fftheora.$! &
		echo $$ / $! > /dev/stderr
	fi
done
